version: '3.7'
services:
  redis:
    image: redis:5.0.5-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - REDIS=redis:6379
    depends_on:
      - redis
    command: 'node server.js'
  frontend:
    image: nginx:1.17.3-alpine
    ports:
      - '8080:80'
    volumes:
      - ./frontend/src:/usr/share/nginx/html
    depends_on:
      - backend
