version: '3'
services:
  redis:
    image: redis:5.0.5-alpine
    ports:
      - '6379:6379'
    volumes:
      - ./data:/data
  backend:
    build: ./backend
    ports:
      - '8000:8000'
    environment:
      - PORT=8000
      - REDIS=redis:6379
